---
version: "3.9"
services:
  web_app:
    build:
      context: .
      args:
        username: user
        port: 3306
        password: Password#
        ip: db_app
        name: sample_db
    depends_on:
      - db_app
    ports:
      - "8090:8080"
  
  db_app:
    image: "mysql:5.7.5"
    volumes: 
      - /home/User/App/DB:/var/lib/mysql
    environment:
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "Password#"
        MYSQL_ROOT_PASSWORD: "SuperSecret"
        MYSQL_DATABASE: "sample_db"